language: C++

services:
    - docker

before_install:
    - sudo apt-get install -y qemu binfmt-support qemu-user-static
    - git clone https://github.com/computermouth/qemu-static-conf.git
    - sudo mkdir -p /lib/binfmt.d
    - sudo cp qemu-static-conf/*.conf /lib/binfmt.d/
    - sudo systemctl restart systemd-binfmt.service
    - cd .devcontainer
    - docker build -f bigendian.Dockerfile .

script: make