language: C++

script:
    - git clone https://github.com/computermouth/qemu-static-conf.git
    - sudo mkdir -p /lib/binfmt.d
    - sudo cp qemu-static-conf/*.conf /lib/binfmt.d/
    - sudo systemctl restart systemd-binfmt.service

services:
    - docker

before_install:
    - cd .devcontainer
    - docker-compose build

#script: make